Feature/enemy model
Calvin-Davidson/Paraphrenia pull request #168
Opened 2023-05-17 08:27 UTC by Aesnas

2023-05-17 09:02 UTC, Calvin-Davidson requested changes
TestMat kan weg?, textures for substance?

2023-05-17 09:21 UTC, Aesnas commented
> TestMat kan weg?, textures for substance?

Ja TestMat kan weg.
Textures for substance is voor Joost om te implementeren in Substance Painter, die zou de enemy model texturen

2023-05-17 09:41 UTC, Calvin-Davidson commented
> > TestMat kan weg?, textures for substance?
> 
> Ja TestMat kan weg. Textures for substance is voor Joost om te implementeren in Substance Painter, die zou de enemy model texturen

Alright, dan laat ik hem even open staan, dit soort files willen we niet persee het project in pushen

2023-05-18 13:10 UTC, Calvin-Davidson requested changes
TestMat.mat mag weg

2023-05-22 07:15 UTC, Calvin-Davidson approved these changes

2023-05-22 07:16 UTC, merged